# Generated by Django 4.1.7 on 2023-03-30 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unities', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_country', models.AutoField(primary_key=True, serialize=False)),
                ('amount_s', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sanctuary',
            fields=[
                ('id_sanctuary', models.AutoField(primary_key=True, serialize=False)),
                ('fk_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephantapiapp.amount')),
                ('fk_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephantapiapp.country')),
            ],
        ),
    ]
